on:
  push:
    tags:
      - '*'
env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true
jobs:
  StageMC:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.0
      - name: Grab tag name
        uses: olegtarasov/get-tag@v2
        id: tagName
      - uses: actions/setup-java@v3.10.0
        with:
          distribution: temurin
          java-version: 17
          cache: gradle
      - name: Upload to Sonatype
        run: |
          ./gradlew publishMavenJavaPublicationToSonatypeStagingRepository \
          -Psign=true \
          -PreleaseVersion="${{ steps.tagName.outputs.tag }}" \
          -PsigningKey="${{ secrets.SIGNING_KEY }}" \
          -PsigningPassword="${{ secrets.SIGNING_PASSWORD }}" \
          -PnexusUsername="${{ secrets.NEXUS_USERNAME }}" \
          -PnexusPassword="${{ secrets.NEXUS_PASSWORD }}"
  ReleaseMC:
    needs: [StageMC]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.0
      - uses: actions/setup-java@v3.10.0
        with:
          distribution: temurin
          java-version: 17
          cache: gradle
      - name: Release to Maven Central
        run: |
          ./gradlew closeAndReleaseRepository \
          -PnexusUsername="${{ secrets.NEXUS_USERNAME }}" \
          -PnexusPassword="${{ secrets.NEXUS_PASSWORD }}"

